---
title: "exercises_0719"
author: "Dane"
date: "2024-07-19"
output: html_document
---

EX 1:

```{r}
library(ggplot2)
library(tidyverse)
books <- read.csv("Books_Data_Clean.csv")
ggplot(books, mapping = aes(x=Author_Rating, y=gross.sales)) +geom_boxplot()
View(books)

```


```{r}
anova_books <- aov(gross.sales~ factor(Author_Rating), data = books) 
summary (anova_books)

```


```{r}
TukeyHSD(anova_books,conf.level = 0.95)
```
```{r}
tukey_result <- TukeyHSD(anova_books, conf.level = 0.95)
tukey_df = as.data.frame(tukey_result$`factor(Author_Rating)`)
tukey_df$comparison <- rownames(tukey_df)
```


```{r}
ggplot(tukey_df, aes(x = comparison, y = diff)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  geom_errorbar(aes(ymin = lwr, ymax = upr), width = 0.2) +
  theme_minimal() +
  labs(title = "Tukey HSD Results",
       x = "Comparison",
       y = "Difference in Means")
```
```{r}
ggplot(tukey_df, aes(x = comparison, y = diff)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  geom_errorbar(aes(ymin = lwr, ymax = upr), width = 0.2) +
  theme_minimal() +
  labs(title = "Tukey HSD Results",
       x = "Comparison",
       y = "Difference in Means") + coord_flip()
```

```{r}
ggplot(tukey_df, aes(x = reorder(comparison, diff), y = diff)) +
  geom_point(size = 4, color = "blue") +
  geom_errorbar(aes(ymin = lwr, ymax = upr), width = 0.2, color = "red") +
  theme_minimal() +
  labs(title = "Tukey HSD Results",
       x = "Comparison",
       y = "Difference in Means") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) +
  coord_flip()
```

